dist: trusty
language: python
branches:
  except:
    - gh-pages
arch: 
  - arm64
  - amd64
python:
  - "3.7"
addons:
  apt:
    packages:
    - build-essential
    - libzmq3-dev
install: ./install-dependencies.sh
script:
  nosetests --with-coverage --cover-package=beaver
after_success:
  coveralls
