dist: trusty
language: python
branches:
  except:
    - gh-pages
arch: 
  - amd64
  - arm64
python:
  - "2.7"
addons:
  apt:
    packages:
    - build-essential
    - libzmq-dev
install: ./install-dependencies.sh
script:
  nosetests --with-coverage --cover-package=beaver
after_success:
  coveralls
